name = "gexcept"
version = "1.0.0"

description = "Exception Handling for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "blobfox", repo = "gexcept" }
links = [{ title = "Website", href = "https://github.com/blobfox/gexcept" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
